resolver: lts-12.2

packages:
- .

extra-deps:
  - HDBC-odbc-2.5.0.1
  # - git: https://github.com/bitemyapp/esqueleto.git
  #   commit: 08c9b4cdf977d5bcd1baba046a007940c1940758
  # - git: https://github.com/bitemyapp/network-api-support.git
  #   commit: f66299ddfe1f4e235d6b8c60811e6fd31480be87
  # - git: https://github.com/yesodweb/wai.git
  #   commit: 6bf765e000c6fd14e09ebdea6c4c5b1510ff5376
  #   subdirs:
  #     - wai-extra
  # - postmark-0.2.3
  # - streaming-commons-0.2.0.0
  # - time-1.9.1
  # - yesod-colonnade-1.3.0.1
  # - yesod-elements-1.1
